---
services:
  alertmanager:
    command:
      - --config.file=/config/isc_alertmanager.yml
      - --data.retention=24h
      - --cluster.listen-address=
    depends_on:
      - iris
      - prometheus
    expose:
      - '9093'
    image: prom/alertmanager:v0.20.0
    restart: on-failure
    volumes:
      - ./config/alertmanager:/config
  grafana:
    depends_on:
      - prometheus
    expose:
      - '3000'
    image: grafana/grafana:6.7.1
    restart: on-failure
    volumes:
      - grafdata:/var/lib/grafana
      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./config/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./config/grafana/dashboard-provider.yml:/etc/grafana/provisioning/dashboards/dashboard-provider.yml
      - ./config/grafana/dashboard.json:/var/lib/grafana/dashboards/dashboard.json
  iris:
    depends_on:
      - iris-init
    environment:
      - ISC_DATA_DIRECTORY=/dur/iconfig
    expose:
      - '51773'
      - '52773'
    hostname: IRIS
    image: containers.intersystems.com/intersystems/sam:1.1.0.107
    init: true
    restart: on-failure
    command: --check-caps false
    volumes:
      - irisdata:/dur
      - ./config:/config
  iris-init:
    command: 'chown -R 51773:51773 /dur'
    image: busybox
    volumes:
      - irisdata:/dur
  nginx:
    depends_on:
      - iris
      - prometheus
      - grafana
    image: nginx:1.17.9-alpine
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
  prometheus:
    command:
      - --web.enable-lifecycle
      - --config.file=/config/isc_prometheus.yml
      - --storage.tsdb.retention.time=2h
    depends_on:
      - iris
    expose:
      - '9090'
    image: prom/prometheus:v2.17.1
    restart: on-failure
    volumes:
      - ./config/prometheus:/config
version: '3.7'
volumes:
  grafdata: ~
  irisdata: ~
